replicaCount: 1

image:
  repository: sonarqube
  tag: community

service:
  type: LoadBalancer
  externalPort: 9000

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

persistence:
  enabled: true
  size: 5Gi

jdbcOverwrite:
  enable: false

postgresql:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  persistence:
    enabled: true
    size: 5Gi

sonarProperties:
  sonar.forceAuthentication: "false"

jvmOpts: "-Xms256m -Xmx512m"

monitoringPasscode: "devops123"

initSysctl:
  enabled: true
  vmMaxMapCount: 524288
  fsFileMax: 131072
  nofile: 131072
  nproc: 8192